# GitHub Action to automate the identification of common misspellings in text files.
# https://github.com/codespell-project/actions-codespell
# https://github.com/codespell-project/codespell
name: codespell
on: [pull_request]

permissions:
  contents: read

jobs:
  codespell:
    if: github.repository == 'cellml/libcellml'
    name: Check for spelling errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: codespell-project/actions-codespell@94259cd8be02ad2903ba34a22d9c13de21a74461 # v2.0
        with:
          check_filenames: true
          skip: tests/gtest/include/gtest/gtest.h,tests/gtest/src/gtest-all.cc,src/dtds/mathml2/*
